name: Llamero Summarization

on:
 push:
    branches:
      - main
 workflow_dispatch:

jobs:
  generate-summaries:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install project
      run: pip install llamero

    - name: Generate summaries
      run: llamero summarize all
